version: "3.7"
services:
   move_front_cam:
      container_name: move_front_cam
      image: manitor_move_front_cam:V1.0
      network_mode: host
      volumes:
         - /dev/bus/usb:/dev/bus/usb
         - /opt/vc:/opt/vc
         - /home/pi/Desktop/demo:/code
         - /tmp/.X11-unix:/tmp/.X11-unix
         - /home/pi/.Xauthority:/root/.Xauthority
      environment:
         LD_LIBRARY_PATH: /opt/vc/lib
         DISPLAY:
      devices:
         - "/dev/vchiq:/dev/vchiq"
      restart: always
      privileged: true
      healthcheck:
         test: [ "CMD","curl","-f", "http://localhost:5006/help" ]
         interval: 1m30s
         timeout: 10s
         retries: 3
         start_period: 40s
