version: "3.7"
services:
   reproduce_audio:
      container_name: reproduce_audio
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 5002:5002
      restart: always
      devices:
         - "/dev/snd:/dev/snd"
      privileged: true
