version: '3.9'
services:
  beacon_scan:
    container_name: beacon_scan
    build:
      context: 1_baliza_scan
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    privileged: true
    healthcheck:
      test: ["CMD","curl","-f", "http://localhost:5001/help"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  send_mqtt:
    container_name: send_mqtt
    build:
      context: 3_send_mqtt
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    environment:
      MAC_CLIENT: dc:a6:32:34:07:0f
      IP_BROKER: 192.168.1.115
      PORT_BROKER: 1883
      NAME_CLIENT: RPI
    restart: always
    healthcheck:
      test: ["CMD","curl","-f", "http://localhost:5003/help"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nombre_persona:
    container_name: nombre_persona
    build:
      context: 4_person_name
      dockerfile: Dockerfile
#    command: tail -f /etc/hosts
    volumes:
      - /home/pi/DATA/history.json:/code/DATA/history.json
      - /home/pi/DATA/BEACON_SCAN.json:/code/DATA/BEACON_SCAN.json
      - /home/pi/DATA/PERSON_SCAN.json:/code/DATA/PERSON_SCAN.json
    ports:
      - 5004:5004
    links:
      - beacon_scan:beacon_scan
    depends_on:
      - beacon_scan
      - send_mqtt
    restart: always
    healthcheck:
      test: ["CMD","curl","-f", "http://localhost:5004/help"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  reproduce_audio:
    container_name: reproduce_audio
    build:
      context: 2_reproduce_audio
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    restart: always
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
    healthcheck:
      test: ["CMD","curl","-f", "http://localhost:5002/help"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  move_front_cam:
    container_name: move_front_cam
    build:
      context: 6_move_front_cam
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /opt/vc:/opt/vc
      - /home/pi/Desktop/demo:/code
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/pi/.Xauthority:/root/.Xauthority
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      DISPLAY:
    devices:
      - "/dev/vchiq:/dev/vchiq"
    restart: always
    privileged: true
    healthcheck:
      test: ["CMD","curl","-f", "http://localhost:5006/help"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  vector:
    container_name: vector
    build:
      context: 7_vector
      dockerfile: Dockerfile
    ports:
      - 5007:5007
    environment:
      MAC_CLIENT: dc:a6:32:34:07:0f
    depends_on:
      - send_mqtt
    restart: always
    privileged: true
    healthcheck:
      test: ["CMD","curl","-f", "http://localhost:5007/help"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  interfaz_video:
    container_name: interfaz_video
    build:
      context: 5_interfaz_video
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /opt/vc:/opt/vc
      - /home/pi/Desktop/demo:/code
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/pi/.Xauthority:/root/.Xauthority
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      DISPLAY:
    devices:
      - "/dev/vchiq:/dev/vchiq"
    privileged: true
