version: "3.7"
services:
   send_mqtt:
      container_name: send_mqtt
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 5003:5003
      environment:
         MAC_CLIENT: dc:a6:32:34:07:0f
         IP_BROKER: 192.168.1.114
         PORT_BROKER: 1883
         NAME_CLIENT: RPI
      restart: always
