version: "3.7"
services:
  interfaz_video:
     container_name: interfaz_video
     build:
        context: .
        dockerfile: Dockerfile
     network_mode: host
     restart: always
     volumes:
        - /dev/bus/usb:/dev/bus/usb
        - /opt/vc:/opt/vc
        - /home/pi/Desktop/demo:/code
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /home/pi/.Xauthority:/root/.Xauthority
     environment:
        LD_LIBRARY_PATH: /opt/vc/lib
        DISPLAY:
     devices:
        - "/dev/vchiq:/dev/vchiq"
     privileged: true
